# Generated by Django 2.2.4 on 2019-10-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('foto', models.CharField(max_length=200)),
                ('perfilProfesional', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portafiolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePortafolio', models.CharField(max_length=200)),
                ('esPublico', models.BooleanField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enlace', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipoDeArchivo', models.CharField(max_length=200)),
                ('esPublica', models.BooleanField()),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kata.Portafiolio')),
            ],
        ),
    ]
